### ISSUE TITLE
One Test case fails

### ISSUE THREAD

**Issue by echorohit** [mjackson/then-redis#53]
I have changed the dependencies to my current redis version and bluebird latest

my package.json is
```
{
  "name": "then-redis",
  "version": "1.3.0",
  "description": "A small, promise-based Redis client",
  "main": "index.js",
  "scripts": {
    "test": "jshint . && mocha --reporter spec 'tests/*-test.js'"
  },
  "repository": {
    "type": "git",
    "url": "git://github.com/mjackson/then-redis.git"
  },
  "dependencies": {
    "bluebird": "^3.0.5",
    "describe-property": "^1.0.0"
  },
  "devDependencies": {
    "expect": "^1.1.0",
    "jshint": "^2.5.10",
    "mocha": "^2.0.1",
    "redis": "^2.3.0"
  },
  "peerDependencies": {
    "redis": "^2.3.0"
  },
  "keywords": [
    "redis",
    "then",
    "promise",
    "promises"
  ],
  "author": "Michael Jackson",
  "license": "MIT"
}

```
And I run this command ``` npm test ```

```
  1) transactions when there is an error executing the transaction returns the error:
     Error: Expected [Error: ERR value is not an integer or out of range] to equal 'ERR value is not an integer or out of range'
      at Object.assert [as default] (node_modules/expect/lib/assert.js:20:9)
      at Expectation.toEqual (node_modules/expect/lib/Expectation.js:89:26)
      at tests/transactions-test.js:24:26
      at tryCatcher (node_modules/bluebird/js/release/util.js:11:23)
      at Promise._settlePromiseFromHandler (node_modules/bluebird/js/release/promise.js:488:31)
      at Promise._settlePromise (node_modules/bluebird/js/release/promise.js:545:18)
      at Promise._settlePromise0 (node_modules/bluebird/js/release/promise.js:590:10)
      at Promise._settlePromises (node_modules/bluebird/js/release/promise.js:673:18)
      at Async._drainQueue (node_modules/bluebird/js/release/async.js:125:16)
      at Async._drainQueues (node_modules/bluebird/js/release/async.js:135:10)
      at Immediate.Async.drainQueues [as _onImmediate] (node_modules/bluebird/js/release/async.js:16:14)
````

**Comment by mjackson** [comment]
This has been fixed.
